### ISSUE TITLE
webgl not supported

### ISSUE THREAD

**Issue by gzzo** [katharostech/bevy_ldtk#8]
It looks like this library can't run on webgl due to something with the shaders. I know this library is not supported anymore officially, but I'm wondering if there is a way to support webgl with this library. Happy to contribute a fix, just need some guidance.

**Comment by zicklag** [comment]
Hey there!

You are correct that WebGL isn't supported because of the shaders. Unfortunately I don't know of a great way to avoid having to write the shaders twice, with one version for web and another version for desktop. I know there are some shader compilers out there, but most of them don't compile desktop shaders to WebGL shaders as far as I know.

I _think_ the only thing necessary would be to convert the shaders in [this folder](https://github.com/katharostech/bevy_ldtk/tree/master/src/pipeline) from GLSL 4.50 to GLSL ES 3.00. That seems to be what the `bevy_webgl2` library has done [here](https://github.com/mrk-its/bevy_webgl2/tree/master/src/shaders), they seem to have re-implemented all of the built-in Bevy shaders in GLSL ES 3.00.

I never got to the point of actually testing that that worked, though so I'm not sure if you would run into other issues. I don't have any experience with `bevy_webgl2` yet so I don't know.

> Happy to contribute a fix, just need some guidance.

Absolutely! I'd be glad to merge anything you come up with if it works. Let me know if you have any other questions.

**Comment by zicklag** [comment]
I've recently discovered that `spirv-cross` is actually capable of compiling GLSL 4.0 to GLSL ES 3.0. I'm not sure if there is a way to do it through the commandline, but I've found that the [rafx](https://github.com/aclysma/rafx) project's shader processor does it using the Rust bindings to `spirv-cross`. That could mean we could automatically convert the shader to version we need, but I still have to do some research.

**Comment by zicklag** [comment]
Just created a gist that shows how to convert the shaders with Rust. I might try it out sometime to see if that fixes web support, but if I don't get to it that's something you can try:

https://gist.github.com/zicklag/4223939751c5bf50094a2a85bd75e411

**Comment by zicklag** [comment]
Well, after looking into the translated shaders I found that we currently use shader features not supported in WebGL. That means that we'd probably have to refactor the way maps are rendered a bit, which is probably better anyway because the maps currently have rendering issues anyway.

Eventually, once bevy's done with their rendering rework that is being discussed [here](https://github.com/bevyengine/bevy/discussions/2351#discussion-3413906), I think we may end up using this library again after porting Bevy Retro to use Bevy's renderer. If that happens that I'll be working on getting this working again.

**Comment by zicklag** [comment]
Bevy LDtk is getting merged into [Bevy Retrograde](https://github.com/katharostech/bevy_retrograde) so I'm closing this issue and archiveing the repo. Soon Bevy Retrograde will support Bevy's renderer ( https://github.com/katharostech/bevy_retrograde/issues/41 ) which will allow you to use `bevy_retrograde_ldtk` alone with out-of-the-box Bevy, removing the need to have separate plugins for Bevy and Bevy Retrograde.

Additionally we are working on integrating Bevy's new renderer with WebGL support so the new LDtk plugin will work with WebGL when we get that working.

You won't be able to comment after the repo is archived, but you can redirect any questions or comments to the Bevy Retrograde [discussions page](https://github.com/katharostech/bevy_retrograde/discussions)!
